sudo: required # sudo is required
services: # install docker
    - docker

before_install: # build the dev verion, so we can run the tests. using tag so we can start it. Relative path to client Dockerfile.dev
    - docker build -t dilipl/react-tests -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dilipl/react-tests npm test -- --coverage # run the tests. coverage makes sure tests exit

# Build prod versions
after_success: 
    - docker build -t dilipl/multi-client ./client
    - docker build -t dilipl/multi-nginx ./nginx
    - docker build -t dilipl/multi-server ./server
    - docker build -t dilipl/multi-worker ./worker

# Login to docker hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take these images and push them to docker hub
    - docker push dilipl/multi-client
    - docker push dilipl/multi-nginx
    - docker push dilipl/multi-server
    - docker push dilipl/multi-worker

# Deploy
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-821957462552'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY