version: '3'
services:
    postgres: # Just run the postgres, container
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api: # calling this api, as it becomes less confusing on nginx side
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules # This is in the /app folder
            - ./server:/app      # This is for source code. Any change we make in server folder locally, the /app in container is mapped to it
        environment: 
            - REDIS_HOST=redis  # this was the service
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules # This is in the /app folder
            - ./worker:/app      # This is for source code. Any change we make in server folder locally, the /app in container is mapped to it
        environment: 
            - REDIS_HOST=redis  # this was the service
            - REDIS_PORT=6379           
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
            - api
            - client    
        ports:
            - '3050:80'